version: '3.8'
services:
  # PostgreSQL Database Service
  basic-3tier-postgres:
    image: postgres:latest
    container_name: basic-3tier-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basic3tier
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - basic3tier

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5431:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - basic-3tier-postgres
    networks:
      - basic3tier

  # # .NET Core WebAPI Service
  webapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: basic-3tier-api
    ports:
      - "7000:80"
    depends_on:
      - basic-3tier-postgres
    environment:
      ConnectionStrings__Basic3Tier: "Host=basic-3tier-postgres;Port=5432;Database=basic3tier;Username=postgres;Password=admin123"
    networks:
      - basic3tier

  # Frontend Application
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: basic-3tier-ui
    ports:
      - "5000:80"
    networks:
      - basic3tier
    volumes:
      - ./ui/configs:/usr/share/nginx/html/configs:ro
    depends_on:
      - webapi
      - basic-3tier-postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  basic3tier:
    name: basic3tier
    driver: bridge

# docker network create basic3tier
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' basic-3tier-postgres
# docker-compose build
# docker-compose up -d
# docker-compose down