apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-store-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/us-central1-a/filestore-instance-sg/filesharesg"
    volumeAttributes:
      ip: 10.53.244.154
      volume: filesharesg
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: podpvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: file-store-pv
  resources:
    requests:
      storage: 1Ti